name: kit_docker_build_lambda_service_image
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  get_it: ^7.6.0
  http: ^0.13.6
  aws_lambda_dart_runtime: ^1.1.0
  aws_lambda_api: ^2.0.0
  aws_apigateway_api: ^2.0.0
  aws_common: ^0.6.3
  aws_signature_v4: ^0.5.1
  kit_dart_utils:
    path: ../../pikobasic/app/packages/kit_dart_utils
  kit_models:
    git: https://github.com/pierreduv/kit_models

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
